name: noefinderlein_flutter
description: Noe Finderlein in Flutter

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.19+2019

environment:
  sdk: ">=2.19.6 <3.0.0"
  # The Flutter version is read in different build scripts and is used to setup the appropriate flutter toolkit.
  # The build processes cannot handle range notations like >=2.17.1 <3.0.0 or ^3.7.0.
  # Therefore it is important to always specify a fixed flutter version in that format: [0-9]+.[0-9]+.[0-9]+
  flutter: 3.10.1

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains the binaries
  path_provider: 2.0.15
  path: ^1.8.2
  http:
  # sqflite:
  # flutter_animation_progress_bar:
  material_design_icons_flutter: 6.0.7096
  url_launcher: 6.1.11
  maps_launcher: ^2.0.1
  flutter_map: ^4.0.0
  # flutter_map_marker_cluster: any
  flutter_map_supercluster: ^4.2.1
  latlong2: ^0.8.1
  flutter_map_location_marker: 6.0.0
  shared_preferences: 2.1.1
  geolocator: ^9.0.2
  intl: any
  package_info_plus: ^4.0.1
  # qr_flutter: ^4.0.0
  # mobile_scanner: ^1.0.0
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  isar_generator: *isar_version
  build_runner: any
  analyzer: any

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: de

# dependency_overrides:
#   geolocator_android:
#     git:
#       name: geolocator_android
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

