name: noefinderlein_flutter
description: Noe Finderlein in Flutter

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: 2.2.1
  isar_flutter_libs: 2.2.1 # contains the binaries
  path_provider: ^2.0.0
  path: ^1.8.0
  http:
  flutter_animation_progress_bar:
  material_design_icons_flutter: 5.0.6595
  url_launcher: ^6.0.20
  maps_launcher: ^2.0.1
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: any
  latlong2: ^0.8.1
  flutter_map_location_marker: any
  shared_preferences: ^2.0.13
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  isar_generator: 2.2.1
  build_runner: ^2.1.8
  analyzer: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
