name: Flutter version
description: Install Specific Flutter version
inputs:
  flutter-version:
    description: The flutter version.
    default: "3.7.9"
  flutter-sdk-channel:
    description: The flutter sdk chanel (stable/beta/master).
    default: "stable"
runs:
  using: "composite"
  steps:
    - name: Install Flutter version
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "${{ inputs.flutter-version }}"
        channel: "${{ inputs.flutter-sdk-channel }}"