name: add secrets
description: Adds a secrets.dart file to lib/auth

inputs:
  mapaccesstoken:
    description: 'A map access token'
    required: true
  mapurl:
    description: 'url to the map'
    required: true
  mapurldark:
    description: 'url to the dark map'
    required: true
  dataapi:
    description: 'Url to the data api'
    required: true

runs:
  using: 'composite'
  steps:
    - name: create lib/auth directory
      shell: bash
      run: mkdir -p lib/auth
    - name: add secrets.dart file
      shell: bash
      run: |
        echo "var mapAccessToken = \"${{ inputs.mapaccesstoken }}\";" >> lib/auth/secrets.dart