name: get version
description: gets the version from the tag

outputs:
  version: 
    description: "version of the build"
    value: ${{ steps.get_version.outputs.VERSION }}
  versionnum: 
    description: "version number of the build"
    value: ${{ steps.get_version.outputs.VERSIONNUM }}


runs:
  using: "composite"
  steps:
    - name: Get the version
      id: get_version
      shell: bash
      run: |
        echo $GITHUB_REF
        BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
        echo $BRANCH_NAME
        GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-10)
        echo $GITHUB_SHA_SHORT
        [[ "$BRANCH_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && OUT=$BRANCH_NAME || OUT=$GITHUB_SHA_SHORT
        echo $OUT
        echo ::set-output name=VERSION::${OUT}
        VNUM=$(cat pubspec.yaml | grep -E "^version:\s.*\+(\d*)" | cut -d+ -f2)
        echo $VNUM
        echo ::set-output name=VERSIONNUM::${VNUM}