name: 🤖 Android Build
on:
  workflow_call:

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > android/release.keystore.asc
          gpg -d --passphrase "${{secrets.ANDROID_RELEASE_KEYSTORE_ENCRYPTION_PASSPHRASE }}" --batch android/release.keystore.asc > android/release.keystore
      - run: |
          echo "storeFile=release.keystore" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSPHRASE }}" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_ALIAS_PW }}"  >> android/key.properties

      - name: Setup secrets
        uses: ./.github/actions/add-secrets
        with:
          mapaccesstoken: ${{ secrets.MAPACCESSTOKEN }}
          mapurl: ${{ secrets.MAPURL }}
          mapurldark: ${{ secrets.MAPURLDARK }}
          dataapi: ${{ secrets.DATAAPI }}
          
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup flutter
        uses: ./.github/actions/flutter-version

      - run: flutter upgrade
      - run: flutter pub get
      - name: generate isar files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab