name: 🍏 iOS Build
on:
  workflow_call:

jobs:
  ios_build:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
      - uses: actions/checkout@v2

      - name: Setup secrets
        uses: ./.github/actions/add-secrets
        with:
          mapaccesstoken: ${{ secrets.MAPACCESSTOKEN }}
          mapurl: ${{ secrets.MAPURL }}
          mapurldark: ${{ secrets.MAPURLDARK }}
          dataapi: ${{ secrets.DATAAPI }}
          
      - name: Setup flutter
        uses: ./.github/actions/flutter-version

      - run: flutter upgrade
      - run: flutter pub get
      - name: generate isar files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable iOS
        run: flutter config --enable-ios
      - name: Build iOS app
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: ios
          path: |
            build/ios/iphoneos/*.app
            build/ios/iphoneos/*.app.