name: 🐧 Windows Build
on:
  workflow_call:
  
jobs:
  appimage_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup secrets
        uses: ./.github/actions/add-secrets
        with:
          mapaccesstoken: ${{ secrets.MAPACCESSTOKEN }}
          mapurl: ${{ secrets.MAPURL }}
          mapurldark: ${{ secrets.MAPURLDARK }}
          dataapi: ${{ secrets.DATAAPI }}
          
      - name: Setup flutter
        uses: ./.github/actions/flutter-version

      - run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - name: generate isar files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - run: |
          tar -C build/linux/x64/release/bundle -cvf noefinderlein-linux-portable.tar.gz .
      - uses: actions/upload-artifact@v3
        with:
          name: tgz
          path: ./*.tar.gz
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: appimage/AppImageBuilder.yml
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
      - uses: actions/upload-artifact@v3
        with:
          name: appimage
          path: ./*.AppImage