name: 🍎 macOS Build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  macos_build:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup secrets
        uses: ./.github/actions/add-secrets
        with:
          mapaccesstoken: ${{ secrets.MAPACCESSTOKEN }}
          
      - name: Setup flutter
        uses: ./.github/actions/flutter-version

      - run: flutter upgrade
      - run: flutter pub get
      - name: generate isar files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable Macos
        run: flutter config --enable-macos-desktop
        run: flutter doctor -v
      - name: Build macOS app
        run: flutter build macos --release
      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg
          cd $MACOS_APP_RELEASE_PATH
          create-dmg \
          --volname "noefinderlein_flutter" \
          --window-pos 200 120 \
          --window-size 800 529 \
          --icon-size 130 \
          --text-size 14 \
          --icon "noefinderlein_flutter.app" 260 250 \
          --hide-extension "noefinderlein_flutter.app" \
          --app-drop-link 540 250 \
          --hdiutil-quiet \
          "noefinderlein_flutter.dmg" \
          "noefinderlein_flutter.app"

      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release/noefinderlein_flutter.dmg