# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v2.*'
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  

  android:
    uses: finderlein/noefinderlein_flutter/.github/workflows/android_build.yml@main
    secrets: inherit

  macos:
    uses: finderlein/noefinderlein_flutter/.github/workflows/macos_build.yml@main
    secrets: inherit

  ios:
    uses: finderlein/noefinderlein_flutter/.github/workflows/ios_build.yml@main
    secrets: inherit

  # web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "2.13.0-0.4.pre"
  #         channel: "beta"
  #     - run: flutter upgrade
  #     - run: flutter pub get
  #     - run: flutter test
  #     - run: flutter build web

  windows:
    uses: finderlein/noefinderlein_flutter/.github/workflows/windows_build.yml@main
    secrets: inherit

  linux:
    uses: finderlein/noefinderlein_flutter/.github/workflows/linux_build.yml@main
    secrets: inherit

  deploy:
    needs: [android, macos, ios, windows, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        uses: ./.github/actions/build-version
      - uses: actions/download-artifact@v3
        with:
          name: android
          path: android
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: android
      - uses: actions/download-artifact@v3
        with:
          name: macos
          path: macos
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: macos
      - uses: actions/download-artifact@v3
        with:
          name: ios
          path: ios
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ios
      - uses: actions/download-artifact@v3
        with:
          name: windows
          path: windows
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: windows
      - uses: actions/download-artifact@v3
        with:
          name: appimage
          path: appimage
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: appimage
      - uses: actions/download-artifact@v3
        with:
          name: tgz
          path: tgz
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: tgz
      - name: rename with version
        run: |
          mv android/bundle/release/app-release.apk android/noefinderlein-android-${{ steps.get_version.outputs.version }}.apk
          mv android/bundle/release/app-release.aab android/noefinderlein-android-${{ steps.get_version.outputs.version }}.aab
          mv macos/noefinderlein_flutter.dmg macos/noefinderlein-macos-${{ steps.get_version.outputs.version }}.dmg
          mv windows/noefinderlein-windows.zip windows/noefinderlein-windows-${{ steps.get_version.outputs.version }}.zip
          mv appimage/NOE.Finderlein-latest-x86_64.AppImage appimage/noefinderlein-linux-${{ steps.get_version.outputs.version }}.AppImage
          mv tgz/noefinderlein-linux-portable.tar.gz tgz/noefinderlein-linux-portable-${{ steps.get_version.outputs.version }}.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get_version.outputs.version }}"
          prerelease: false
          title: "NÖ Finderlein Release ${{ steps.get_version.outputs.version }}"
          files: |
            android/noefinderlein-android-${{ steps.get_version.outputs.version }}.apk
            android/noefinderlein-android-${{ steps.get_version.outputs.version }}.aab
            macos/noefinderlein-macos-${{ steps.get_version.outputs.version }}.dmg
            windows/noefinderlein-windows-${{ steps.get_version.outputs.version }}.zip
            appimage/noefinderlein-linux-${{ steps.get_version.outputs.version }}.AppImage
            tgz/noefinderlein-linux-portable-${{ steps.get_version.outputs.version }}.tar.gz
            # ios/**/*.app
            # ios/**/*.app.
            # ios/*.app
            # ios/*.app.