# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v2.*'
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  

  android:
    uses: finderlein/noefinderlein_flutter/.github/workflows/android_build.yml@main
    secrets: inherit

  macos:
    uses: finderlein/noefinderlein_flutter/.github/workflows/macos_build.yml@main
    secrets: inherit

  ios:
    uses: finderlein/noefinderlein_flutter/.github/workflows/ios_build.yml@main
    secrets: inherit

  # web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "2.13.0-0.4.pre"
  #         channel: "beta"
  #     - run: flutter upgrade
  #     - run: flutter pub get
  #     - run: flutter test
  #     - run: flutter build web

  windows:
    uses: finderlein/noefinderlein_flutter/.github/workflows/windows_build.yml@main
    secrets: inherit

  linux:
    uses: finderlein/noefinderlein_flutter/.github/workflows/linux_build.yml@main
    secrets: inherit

  deploy_android_build:
    needs: [android]
    uses: finderlein/noefinderlein_flutter/.github/workflows/deploy_android_build.yml@main
    secrets: inherit

  deploy:
    needs: [android, macos, ios, windows, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        uses: ./.github/actions/build-version

      - uses: actions/download-artifact@v3
        with:
          name: android-down
          path: android-down
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: android-down

      - uses: actions/download-artifact@v3
        with:
          name: macos-down
          path: macos-down
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: macos-down

      - uses: actions/download-artifact@v3
        with:
          name: ios-down
          path: ios-down
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ios-down

      - uses: actions/download-artifact@v3
        with:
          name: windows-down
          path: windows-down
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: windows-down

      - uses: actions/download-artifact@v3
        with:
          name: appimage-down
          path: appimage-down
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: appimage-down

      - uses: actions/download-artifact@v3
        with:
          name: tgz-down
          path: tgz-down
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: tgz-down

      - name: rename with version
        run: |
          mv android-down/flutter-apk/app-release.apk android-down/noefinderlein-android-${{ steps.get_version.outputs.version }}.apk
          mv android-down/bundle/release/app-release.aab android-down/noefinderlein-android-${{ steps.get_version.outputs.version }}.aab
          mv macos-down/noefinderlein_flutter.dmg macos-down/noefinderlein-macos-${{ steps.get_version.outputs.version }}.dmg
          mv windows-down/noefinderlein-windows.zip windows-down/noefinderlein-windows-${{ steps.get_version.outputs.version }}.zip
          mv appimage-down/NOE.Finderlein-latest-x86_64.AppImage appimage-down/noefinderlein-linux-${{ steps.get_version.outputs.version }}.AppImage
          mv tgz-down/noefinderlein-linux-portable.tar.gz tgz-down/noefinderlein-linux-portable-${{ steps.get_version.outputs.version }}.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get_version.outputs.version }}"
          prerelease: false
          title: "NÖ Finderlein Release ${{ steps.get_version.outputs.version }}"
          files: |
            android-down/noefinderlein-android-${{ steps.get_version.outputs.version }}.apk
            android-down/noefinderlein-android-${{ steps.get_version.outputs.version }}.aab
            macos-down/noefinderlein-macos-${{ steps.get_version.outputs.version }}.dmg
            windows-down/noefinderlein-windows-${{ steps.get_version.outputs.version }}.zip
            appimage-down/noefinderlein-linux-${{ steps.get_version.outputs.version }}.AppImage
            tgz-down/noefinderlein-linux-portable-${{ steps.get_version.outputs.version }}.tar.gz
            # ios/**/*.app
            # ios/**/*.app.
            # ios/*.app
            # ios/*.app.