name: 🏁 Windows Build
on:
  workflow_call:

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup secrets
        uses: ./.github/actions/add-secrets
        with:
          mapaccesstoken: ${{ secrets.MAPACCESSTOKEN }}

      - name: Setup flutter
        uses: ./.github/actions/flutter-version

      - run: flutter pub get
      - name: generate isar files
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - name: Zip Folder
        run: Compress-Archive -Path 'build\*' -DestinationPath 'noefinderlein-windows.zip'
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./noefinderlein-windows.zip